const SENTENCES = [
  {
    jpWords: [
      "わたし",
      "の",
      "あかい",
      "コート",
      "は",
      "どこ",
      "です",
      "か",
      "。",
    ],
    en: ["Where is my red coat?"],
    notes: [],
    types: [],
    tags: [],
  },
  {
    jpWords: ["おもしろい", "えいが", "を", "見ます", "か", "。"],
    en: ["Do you watch funy movies?"],
    notes: [],
    types: [],
    tags: [],
  },
  {
    jpWords: [
      "中山",
      "さん",
      "は",
      "十一時",
      "に",
      "サンドイッチ",
      "を",
      "たべます",
      "。",
    ],
    en: ["Mr. Nakayama eats a sandwich at eleven o clock."],
    notes: [],
    types: [],
    tags: [],
  },
  {
    jpWords: ["はい", "、", "よく", "ジャズ", "を", "ききます", "。"],
    en: ["Yes, I often listen to jazz."],
    notes: [],
    types: [],
    tags: [],
  },
  {
    jpWords: [
      "なおみ",
      "さん",
      "は",
      "ときどき",
      "アニメ",
      "を",
      "見ます",
      "。",
    ],
    en: ["Naomi sometimes watches anime"],
    notes: [],
    types: [],
    tags: [],
  },
  {
    jpWords: ["中山", "さん", "は", "よく", "やきゅう", "を", "します", "。"],
    en: ["Ms. Nakayama often plays baseball"],
    notes: [],
    types: [],
    tags: [],
  },
  {
    jpWords: ["これ", "は", "バスケットボール", "じゃないです", "。"],
    en: [`This isn't basketball.`],
    notes: [],
    types: [],
    tags: [],
  },
  {
    jpWords: ["まいにち", "おいしい", "パン", "を", "たべます", "。"],
    en: ["I eat tasty bread every day"],
    notes: [],
    types: [],
    tags: [],
  },
];

export default SENTENCES;
