import { CLOTHES, FOOD, SIZE, TIME } from "../TAGS";
import { ADJECTIVE, KANJI } from "../TYPES";

const defaultWord = [
    {
        kana: '',
        kanji: '',
        en: [],
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
]

 const ADJECTIVES  = [
    {
        kana: 'おしゃれ',
        en: ['Fashionable'],
        tags: [CLOTHES],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ときどき',
        en: ['Sometimes'],
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'よく',
        en: ['Often'],
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'あたまがいい',
        en: ['Smart'],
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ゆうめい',
        en: ['Famous'],
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'うるさい',
        en: ['Noisy'],
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'いそがしい',
        en: ['Busy'],
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'とても',
        en: ['Very'],
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'きれい',
        en: ['Clean'],
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'しずか',
        en: ['Quiet'],
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'にぎやか',
        en: ['Lively'],
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    //TODO
    {
        kana: 'おもしろい',
        en: ['Fun','funny','interesting'],
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'あかるい',
        en: ['Cheerfull'],
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'かわいい',
        en: ['Cute', 'Cuter', 'Pretty'],
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ちいさい',
        en: ['Small','Little'],
        tags: [SIZE],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'おおき',
        en: ['Big','Large'],
        tags: [SIZE],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'おいしい',
        en: ['Tasty', 'Good','Delicious'],
        tags: [FOOD],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'かっこいい',
        en: ['Cool','Good-looking','Stylish'],
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'やさしい',
        en: ['Kind','Easy','Nice'],
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
];

export default ADJECTIVES