import { CLOTHES, FOOD, SIZE, TIME } from "../TAGS";
import { ADJECTIVE, KANJI } from "../TYPES";

const defaultWord = [
    {
        kana: '',
        kanji: '',
        en: [],
        sound: '',
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
]

 const ADJECTIVES  = [
    {
        kana: 'おしゃれ',
        kanji: '',
        en: ['Fashionable'],
        sound: 'oshare',
        tags: [CLOTHES],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ときどき',
        kanji: '',
        en: ['Sometimes'],
        sound: 'tokidoki',
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'よく',
        kanji: '',
        en: ['Often'],
        sound: 'yoku',
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'あたまがいい',
        kanji: '',
        en: ['Smart'],
        sound: 'atamagaii',
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ゆうめい',
        kanji: '',
        en: ['Famous'],
        sound: 'yuumei',
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'うるさい',
        kanji: '',
        en: ['Noisy'],
        sound: 'urusai',
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'いそがしい',
        kanji: '',
        en: ['Busy'],
        sound: 'isogashii',
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'とても',
        en: ['Very'],
        sound: 'totemo',
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'きれい',
        en: ['Clean'],
        sound: 'kirei',
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'しずか',
        en: ['Quiet'],
        sound: 'shizuka',
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'にぎやか',
        en: ['Lively'],
        sound: 'nigiyaka',
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    //TODO
    {
        kana: 'おもしろい',
        kanji: '',
        en: ['Fun','funny','interesting'],
        sound: 'omoshiroi',
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'あかるい',
        kanji: '',
        en: ['Cheerfull'],
        sound: 'akarui',
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'かわいい',
        kanji: '',
        en: ['Cute', 'Cuter', 'Pretty'],
        sound: 'kawaii',
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ちいさい',
        kanji: '',
        en: ['Small','Little'],
        sound: 'chiisaii',
        tags: [SIZE],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'おおき',
        kanji: '',
        en: ['Big','Large'],
        sound: 'ooki',
        tags: [SIZE],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'おいしい',
        kanji: '',
        en: ['Tasty', 'Good','Delicious'],
        sound: 'oishii',
        tags: [FOOD],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'かっこいい',
        kanji: '',
        en: ['Cool','Good-looking','Stylish'],
        sound: 'kakkoii',
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'やさしい',
        kanji: '',
        en: ['Kind','Easy','Nice'],
        sound: 'yasashii',
        tags: [],
        types: [ADJECTIVE],
        notes: [],
        difficulty: 1,
    },
];

export default ADJECTIVES