import { CLOTHES, COUNTRY, DRINK, ENTERTAINMENT, FOOD, LOCATION, MUSIC, NATIONALITY, OCCUPATION, PERSON, PLACE, SPORT, TECH, THING, TRANSPORT, VACATION } from "../TAGS";
import { FOREIGN } from "../TYPES";

const defaultWord = [
    {
        kana: '',
        kanji: '',
        en: [],
        sound: '',
        tags: [],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
]

 const FOREIGNS  = [
    {
        kana: 'コーヒー',
        kanji: '',
        en: ['Coffee'],
        sound: 'koohii',
        tags: [FOOD, THING,DRINK],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ジュース',
        kanji: '',
        en: ['Juice'],
        sound: 'juice',
        tags: [FOOD, THING,DRINK],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'パン',
        kanji: '',
        en: ['Bread'],
        sound: 'pan',
        tags: [FOOD, THING],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'サンドイッチ',
        kanji: '',
        en: ['Sandwich'],
        sound: 'sandoicchi',
        tags: [FOOD, THING],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'Jポップ',
        kanji: '',
        en: ['J pop'],
        sound: 'jpoppu',
        tags: [ENTERTAINMENT,MUSIC],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'アニメ',
        kanji: '',
        en: ['Anime'],
        sound: 'anime',
        tags: [ENTERTAINMENT],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ニュース',
        kanji: '',
        en: ['News'],
        sound: 'nyuusu',
        tags: [ENTERTAINMENT],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ロㇱク',
        kanji: '',
        en: ['Rock'],
        sound: 'rokku',
        tags: [MUSIC],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ジャズ',
        kanji: '',
        en: ['Jazz'],
        sound: 'jyazu',
        tags: [MUSIC],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'サッカー',
        kanji: '',
        en: ['Soccer'],
        sound: 'sakkaa',
        tags: [SPORT],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'バスケットボール',
        kanji: '',
        en: ['Basketball'],
        sound: 'basukettobooru',
        tags: [SPORT],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'テレビ',
        kanji: '',
        en: ['TV'],
        sound: 'terebi',
        tags: [TECH],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'インジニア',
        en: ['Engineer'],
        sound: 'injinia',
        tags: [PERSON, OCCUPATION],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ニューヨーク',
        kanji: '',
        en: ['New York'],
        sound: 'nyuuyooku',
        tags: [PLACE],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'パスポート',
        kanji: '',
        en: ['Passport'],
        sound: 'pasupooto',
        tags: [TRANSPORT,  THING],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'スマホ',
        kanji: '',
        en: ['Smartphone'],
        sound: 'sumaho',
        tags: [TECH, THING],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'コート',
        kanji: '',
        en: ['Coat(s)'],
        sound: 'kooto',
        tags: [CLOTHES],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'デパート',
        kanji: '',
        en: ['Department store'],
        sound: 'depaato',
        tags: [LOCATION],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'バステい',
        kanji: '',
        en: ['Bus stop'],
        sound: 'basutei',
        tags: [TRANSPORT],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ホテル',
        kanji: '',
        en: ['Hotel'],
        sound: 'hoteru',
        tags: [LOCATION,VACATION],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'コンビニ',
        kanji: '',
        en: ['Convenience store'],
        sound: 'konbini',
        tags: [FOOD, LOCATION],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ブラジル',
        kanji: '',
        en: ['Brazil'],
        sound: 'burajiru',
        tags: [COUNTRY,PLACE],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ブラジルじん',
        kanji: '',
        en: ['Brazzilian nationality'],
        sound: 'burajiru',
        tags: [COUNTRY,PLACE,PERSON,NATIONALITY],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'カナダ',
        kanji: '',
        en: ['Canada'],
        sound: 'kanada',
        tags: [COUNTRY,PLACE],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'カナダじん',
        kanji: '',
        en: ['Canadian nationality'],
        sound: 'kanadajin',
        tags: [COUNTRY,PLACE,PERSON,NATIONALITY],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'イギリス',
        kanji: '',
        en: ['England'],
        sound: 'igirisu',
        tags: [COUNTRY,PLACE],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'イギリスじん',
        kanji: '',
        en: ['English nationality'],
        sound: 'igirisu',
        tags: [COUNTRY,PLACE,PERSON,NATIONALITY],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'アメリカ',
        kanji: '',
        en: ['America'],
        sound: 'amerika',
        tags: [COUNTRY,PLACE],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'アメリカじん',
        kanji: '',
        en: ['American nationality'],
        sound: 'amerikajin',
        tags: [COUNTRY,PLACE,PERSON,NATIONALITY],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ケーキ',
        kanji: '',
        en: ['Cake'],
        sound: 'keeki',
        tags: [FOOD],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ピザ',
        kanji: '',
        en: ['Pizza'],
        sound: 'piza',
        tags: [FOOD],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ラーメン',
        kanji: '',
        en: ['Ramen'],
        sound: 'ramen',
        tags: [FOOD],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'カレー',
        kanji: '',
        en: ['Curry'],
        sound: 'karee',
        tags: [FOOD],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
];

export default FOREIGNS