import { CLOTHES, COUNTRY, DRINK, ENTERTAINMENT, FOOD, LOCATION, MUSIC, NATIONALITY, OCCUPATION, PERSON, PLACE, SPORT, TECH, THING, TRANSPORT, VACATION } from "../TAGS";
import { FOREIGN } from "../TYPES";

const defaultWord = [
    {
        kana: '',
        en: [],
        tags: [],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
]

 const FOREIGNS  = [
    {
        kana: 'コーヒー',
        en: ['Coffee'],
        tags: [FOOD, THING,DRINK],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ジュース',
        en: ['Juice'],
        tags: [FOOD, THING,DRINK],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'パン',
        en: ['Bread'],
        tags: [FOOD, THING],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'サンドイッチ',
        en: ['Sandwich'],
        tags: [FOOD, THING],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'Jポップ',
        en: ['J pop'],
        tags: [ENTERTAINMENT,MUSIC],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'アニメ',
        en: ['Anime'],
        tags: [ENTERTAINMENT],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ニュース',
        en: ['News'],
        tags: [ENTERTAINMENT],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ロック',
        en: ['Rock'],
        tags: [MUSIC],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ジャズ',
        en: ['Jazz'],
        tags: [MUSIC],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'サッカー',
        en: ['Soccer'],
        tags: [SPORT],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'バスケットボール',
        en: ['Basketball'],
        tags: [SPORT],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'テレビ',
        en: ['TV'],
        tags: [TECH],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'インジニア',
        en: ['Engineer'],
        tags: [PERSON, OCCUPATION],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ニューヨーク',
        en: ['New York'],
        tags: [PLACE],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'パスポート',
        en: ['Passport'],
        tags: [TRANSPORT,  THING],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'スマホ',
        en: ['Smartphone'],
        tags: [TECH, THING],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'コート',
        en: ['Coat(s)'],
        tags: [CLOTHES],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'デパート',
        en: ['Department store'],
        tags: [LOCATION],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'バステい',
        en: ['Bus stop'],
        tags: [TRANSPORT],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ホテル',
        en: ['Hotel'],
        tags: [LOCATION,VACATION],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'コンビニ',
        en: ['Convenience store'],
        tags: [FOOD, LOCATION],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ブラジル',
        en: ['Brazil'],
        tags: [COUNTRY,PLACE],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ブラジルじん',
        en: ['Brazzilian nationality'],
        tags: [COUNTRY,PLACE,PERSON,NATIONALITY],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'カナダ',
        en: ['Canada'],
        tags: [COUNTRY,PLACE],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'カナダじん',
        en: ['Canadian nationality'],
        tags: [COUNTRY,PLACE,PERSON,NATIONALITY],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'イギリス',
        en: ['England'],
        tags: [COUNTRY,PLACE],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'イギリスじん',
        en: ['English nationality'],
        tags: [COUNTRY,PLACE,PERSON,NATIONALITY],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'アメリカ',
        en: ['America'],
        tags: [COUNTRY,PLACE],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'アメリカじん',
        en: ['American nationality'],
        tags: [COUNTRY,PLACE,PERSON,NATIONALITY],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ケーキ',
        en: ['Cake'],
        tags: [FOOD],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ピザ',
        en: ['Pizza'],
        tags: [FOOD],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ラーメン',
        en: ['Ramen'],
        tags: [FOOD],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'カレー',
        en: ['Curry'],
        tags: [FOOD],
        types: [FOREIGN],
        notes: [],
        difficulty: 1,
    },
];

export default FOREIGNS