import { CLOTHES, COLOR, COUNTRY, DRINK, ENTERTAINMENT, FAMILY, FOOD, HOUSE, MEDICINE, MUSIC, NATIONALITY, OCCUPATION, PERSON, PLACE, RAIN, SCHOOL, SPORT, THING, TRANSPORT } from "../TAGS";
import { KANJI, NOUN } from "../TYPES";

const defaultWord = [
    {
        kana: '',
        kanji: '',
        en: [],
        sound: '',
        tags: [],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
]

 const NOUNS  = [
    {
        kana: 'べんとう',
        kanji: '',
        en: ['Boxed lunch'],
        sound: 'bentoo',
        tags: [FOOD],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'あさごはん',
        kanji: '',
        en: ['Breakfast'],
        sound: 'asagohan',
        tags: [FOOD],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ひるごはん',
        kanji: '',
        en: ['Lunch'],
        sound: 'hirugohan',
        tags: [FOOD],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ばんごはん',
        kanji: '',
        en: ['Dinner'],
        sound: 'bangohan',
        tags: [FOOD],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'まんが',
        kanji: '',
        en: ['Manga'],
        sound: 'manga',
        tags: [ENTERTAINMENT],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'やきゅう',
        kanji: '',
        en: ['Baseball'],
        sound: 'yakyuu',
        tags: [SPORT],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ざっし',
        kanji: '',
        en: ['magazine'],
        sound: 'zasshi',
        tags: [ENTERTAINMENT, THING],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        furi: ['ほん'],
        kanji: '本',
        en: ['Books'],
        sound: 'hon',
        tags: [ENTERTAINMENT, THING],
        types: [NOUN, KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'おんがく',
        kanji: '',
        en: ['Music'],
        sound: 'ongaku',
        tags: [MUSIC, ENTERTAINMENT],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'えいが',
        kanji: '',
        en: ['Movies'],
        sound: 'eiga',
        tags: [ENTERTAINMENT],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'かいしゃいん',
        kanji: '',
        en: ['Office worker'],
        sound: 'kaishyain',
        tags: [OCCUPATION,PERSON],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'かんごし',
        kanji: '',
        en: ['Nurse'],
        sound: 'kangoshi',
        tags: [OCCUPATION,PERSON, MEDICINE],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    //FAMILY
    {
        kana: 'かぞく',
        en: ['Family'],
        sound: 'kazoku',
        tags: [PERSON, FAMILY],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'つま',
        en: ['Wife'],
        sound: 'tsuma',
        tags: [PERSON, FAMILY],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'おっと',
        en: ['Husband'],
        sound: 'otto',
        tags: [PERSON, FAMILY],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'むすめ',
        en: ['Daughter'],
        sound: 'musume',
        tags: [PERSON, FAMILY],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'むすこ',
        en: ['Son'],
        sound: 'musuko',
        tags: [PERSON, FAMILY],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'いもうと',
        kanji: '',
        en: ['Younger sister'],
        sound: 'imooto',
        tags: [PERSON, FAMILY],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'あね',
        kanji: '',
        en: ['Older sister'],
        sound: 'ane',
        tags: [PERSON, FAMILY],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'おとうと',
        kanji: '',
        en: ['Younger brother'],
        sound: 'otooto',
        tags: [PERSON, FAMILY],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'あに',
        kanji: '',
        en: ['Older brother'],
        sound: 'ani',
        tags: [PERSON, FAMILY],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        furi: ['ちち'],
        kanji: '父',
        en: ['Dad'],
        sound: 'chichi',
        tags: [PERSON, FAMILY],
        types: [NOUN,KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        furi: ['はは'],
        kanji: '母',
        en: ['Mom'],
        sound: 'haha',
        tags: [PERSON, FAMILY],
        types: [NOUN,KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'まち',
        en: ['Town', 'Wait', 'City'],
        sound: 'machi',
        tags: [PLACE],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'とし',
        kanji: '',
        en: ['City'],
        sound: 'toshi',
        tags: [PLACE],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'おおさか',
        en: ['Osaka'],
        sound: 'osaka',
        tags: [PLACE],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        furi: ['きょう','と'],
        kanji: '京都',
        en: ['Kyoto'],
        sound: 'kyooto',
        tags: [PLACE],
        types: [NOUN, KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'かばん',
        kanji: '',
        en: ['bag'],
        sound: 'kaban',
        tags: [THING],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: '',
        kanji: '田中',
        furi:['た','なか'],
        en: ['Tanaka last name'],
        sound: 'tanaka',
        tags: [PERSON],
        types: [NOUN,KANJI],
        notes: [],
        difficulty: 1,
    },
    //Numbers
    {
        kana: 'いち',
        furi:['いち'],
        kanji: '一',
        en: ['One','An', 'A'],
        sound: 'ichi',
        tags: [],
        types: [NOUN, KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'に',
        furi:['に'],
        kanji: '二',
        en: ['Two'],
        sound: 'ni',
        tags: [],
        types: [NOUN, KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'さん',
        furi:['さん'],
        kanji: '三',
        en: ['Three', 'Third'],
        sound: 'san',
        tags: [],
        types: [NOUN, KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'よん',
        furi:['よん'],
        kanji: '四',
        en: ['Four'],
        sound: 'yon',
        tags: [],
        types: [NOUN, KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ご',
        furi:['ご'],
        kanji: '五',
        en: ['Five'],
        sound: 'go',
        tags: [],
        types: [NOUN, KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ろく',
        furi:['ろく'],
        kanji: '六',
        en: ['Six'],
        sound: 'roku',
        tags: [],
        types: [NOUN, KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'なな',
        furi:['なな'],
        kanji: '七',
        en: ['Seven'],
        sound: 'nana',
        tags: [],
        types: [NOUN, KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'はち',
        furi:['はち'],
        kanji: '八',
        en: ['Eight'],
        sound: 'hachi',
        tags: [],
        types: [NOUN, KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'きゅう',
        furi:['きゅう'],
        kanji: '九',
        en: ['Nine'],
        sound: 'kyuu',
        tags: [],
        types: [NOUN, KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'じゅう',
        furi:['じゅう'],
        kanji: '十',
        en: ['Ten'],
        sound: 'jyuu',
        tags: [],
        types: [NOUN, KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'しろい',
        kanji: '',
        en: ['White'],
        sound: 'shiroi',
        tags: [COLOR],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'あかい',
        kanji: '',
        en: ['Red'],
        sound: 'akai',
        tags: [COLOR],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ぼうし',
        kanji: '',
        en: ['Hat(s)'],
        sound: 'booshi',
        tags: [CLOTHES],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'えき',
        kanji: '',
        en: ['Station(s)','Train station(s)'],
        sound: 'eki',
        tags: [TRANSPORT],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'にほん',
        furi: ['に','ほん'],
        kanji: '日本',
        en: ['Japan'],
        sound: 'nihon',
        tags: [COUNTRY,PLACE],
        types: [NOUN,KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'にほんじん',
        furi: ['に','ほん'],
        kanji: '日本じん',
        en: ['Japanese nationality'],
        sound: 'nihonjin',
        tags: [COUNTRY,PLACE,PERSON,NATIONALITY],
        types: [NOUN,KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'だいがく',
        kanji: '',
        en: ['University','College'],
        sound: 'daigaku',
        tags: [SCHOOL],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'だいがくせい',
        kanji: '',
        en: ['College student','College students'],
        sound: 'daigakusei',
        tags: [SCHOOL],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'がくせい',
        kanji: '',
        en: ['Student','Students'],
        sound: 'gakusei',
        tags: [SCHOOL],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ひと',
        kanji: '',
        en: ['Person', 'People'],
        sound: 'shito',
        tags: [],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'べんごし',
        kanji: '',
        en: ['Lawyer', 'Lawyers'],
        sound: 'bengoshi',
        tags: [OCCUPATION],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'せんせい',
        kanji: '',
        en: ['Teacher', 'Teachers','Professor'],
        sound: 'sensei',
        tags: [OCCUPATION],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'いしゃ',
        kanji: '',
        en: ['Doctor','Doctors'],
        sound: 'ishya',
        tags: [OCCUPATION],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ちかてつ',
        kanji: '',
        en: ['Subway'],
        sound: 'chikatetsu',
        tags: [TRANSPORT],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'かさ',
        kanji: '',
        en: ['Umbrella'],
        sound: 'kasa',
        tags: [THING, RAIN],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {     
        kana: 'きっぷ',
        kanji: '',    
        en: ['Ticket'],
        sound: 'kippu',
        tags: [TRANSPORT, THING],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'くつ',
        kanji: '',
        en: ['Shoe(s)'],
        sound: 'kutsu',
        tags: [CLOTHES,HOUSE],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ちず',
        kanji: '',
        en: ['Map'],
        sound: 'chizu',
        tags: [TRANSPORT, THING],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'くうこう',
        kanji: '',
        en: ['Airport'],
        sound: 'kuukoo',
        tags: [TRANSPORT],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'みず',
        kanji: '',
        en: ['Water', 'Waters'],
        sound: 'mizu',
        tags: [DRINK],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'おちゃ',
        kanji: '',
        en: ['Green tea','Tea'],
        sound: 'ochia',
        tags: [DRINK],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ごはん',
        kanji: '',
        en: ['Rice','Meal','Meals'],
        sound: 'gohan',
        tags: [FOOD],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'すし',
        kanji: '',
        en: ['Sushi'],
        sound: 'sushi',
        tags: [FOOD],
        types: [NOUN],
        notes: [],
        difficulty: 1,
    },
];

export default NOUNS