import { FORMALITY, GREETING, LOCATION, TIME, NUMBER, PERSON } from "../TAGS";
import { OTHER, PARTICLE,KANJI } from "../TYPES";

const defaultWord = [
    {
        kana: '',
        kanji: '',
        en: [],
        sound: '',
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
]

 const OTHERS  = [
    {
        kana: 'ごろ',
        kanji: '',
        en: ['Similar', 'Like'],
        sound: 'goro',
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'さよなら',
        kanji: '',
        en: ['Bye'],
        sound: 'sayonara',
        tags: [GREETING],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'またあした',
        kanji: '',
        en: ['See you tomorrow'],
        sound: 'mataashita',
        tags: [GREETING],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'おなまえは',
        kanji: '',
        en: ['Whats your name'],
        sound: 'onamaewa',
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'はじめまして',
        kanji: '',
        en: ['Nice to meet you'],
        sound: 'hajimemashite',
        tags: [GREETING],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'どうぞよろしく',
        kanji: '',
        en: ['Nice to meet you'],
        sound: 'doozoyoroshiku',
        tags: [GREETING],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: ['しゅっしん'],
        en: ['Being from', 'is from'],
        sound: 'shusshin',
        tags: [LOCATION],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        furi: ['はん'],
        kanji: '半',
        en: ['Thirty', 'Half'],
        sound: 'han',
        tags: [TIME, NUMBER],
        types: [KANJI, OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        furi: ['く','じ'],
        kanji: '九時',
        en: ['Nine o clock'],
        sound: 'kuji',
        tags: [TIME,NUMBER],
        types: [KANJI, OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        furi: ['しち','じ'],
        kanji: '七時',
        en: ['Seven o clock'],
        sound: 'shichiji',
        tags: [TIME,NUMBER],
        types: [KANJI, OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        furi: ['なん'],
        kanji:'何',
        en: ['What'],
        sound: 'nan',
        tags: [],
        types: [OTHER, KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        furi: ['じん'],
        en: ['Nationality'],
        sound: 'ji',
        tags: [PERSON],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        furi: ['じ'],
        kanji: '時',
        en: ['o clock'],
        sound: 'ji',
        tags: [TIME],
        types: [KANJI, OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'まいあさ',
        kanji: '',
        en: ['Every morning'],
        sound: 'maiasa',
        tags: [TIME],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'まいにち',
        kanji: '',
        en: ['Every day'],
        sound: 'mainichi',
        tags: [TIME],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'まいばん',
        kanji: '',
        en: ['Every night'],
        sound: 'maiban',
        tags: [TIME],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'を',
        kanji: '',
        en: ['Through', 'With', 'For'],
        sound: 'o',
        tags: [],
        types: [OTHER],
        notes: ['Goes before verbs'],
        difficulty: 1,
    },
    {
        kana: 'さい',
        kanji: '',
        en: ['Years old', '(n) of age'],
        sound: 'sai',
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ようこそ',
        kanji: '',
        en: ['Welcome'],
        sound: 'yookoso',
        tags: [FORMALITY],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'いらっしゃいませ',
        kanji: '',
        en: ['Welcome'],
        sound: 'irasshaimase',
        tags: [GREETING, FORMALITY],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'おはようございます',
        kanji: '',
        en: ['Good morning'],
        sound: 'ohayoogozaimasu',
        tags: [FORMALITY],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'すみません',
        kanji: '',
        en: ['Excuse me'],
        sound: 'sumimasen',
        tags: [FORMALITY],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'いま',
        kanji: '',
        en: ['Now', 'Current'],
        sound: 'ima',
        tags: [TIME],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'どう',
        en: ['What about', 'How is'],
        sound: 'doo',
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'も',
        en: ['Also', 'Even', 'Any'],
        sound: 'mo',
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        furi: ['わたし'],
        kanji: '私',
        en: ['I'],
        sound: 'watashi',
        tags: [],
        types: [OTHER, PARTICLE, KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'か',
        kanji: '',
        en: ['Is it?','That','Or'],
        sound: 'ka',
        tags: [],
        types: [OTHER, PARTICLE],
        notes: ['Used at the end to ask something'],
        difficulty: 1,
    },
    {
        kana: 'はい',
        kanji: '',
        en: ['Yes'],
        sound: 'hai',
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'いいえ',
        kanji: '',
        en: ['No'],
        sound: 'iie',
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'じゃあね',
        kanji: '',
        en: ['Bye'],
        sound: 'jyane',
        tags: [GREETING],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'さん',
        kanji: '',
        en: ['Mr','Miss','Mrs'],
        sound: 'san',
        tags: [FORMALITY],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'こんにちは',
        kanji: '',
        en: ['Hello'],
        sound: 'konnichiwa',
        tags: [GREETING],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'は',
        kanji: '',
        en: ['Is','With','Regarding'],
        sound: 'wa',
        tags: [],
        types: [OTHER,PARTICLE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'に',
        kanji: '',
        en: ['To', 'In', 'As (a)'],
        sound: 'ni',
        tags: [],
        types: [OTHER,PARTICLE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'と',
        kanji: '',
        en: ['And', 'That', 'Door'],
        sound: 'to',
        tags: [],
        types: [OTHER, PARTICLE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'の',
        kanji: '',
        en: ['Of','One'],
        sound: 'no',
        tags: [],
        types: [OTHER, PARTICLE],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'この',
        kanji: '',
        en: ['This'],
        sound: 'kono',
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'その',
        kanji: '',
        en: ['The','That','Its'],
        sound: 'sono',
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'これ',
        kanji: '',
        en: ['This', 'This (one)','It'],
        sound: 'kore',
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'それ',
        kanji: '',
        en: ['That', 'That (one)'],
        sound: 'sore',
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'あれ',
        kanji: '',
        en: ['That over there', 'That (one) over there'],
        sound: 'are',
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ここ',
        kanji: '',
        en: ['Here'],
        sound: 'koko',
        tags: [LOCATION],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'そこ',
        kanji: '',
        en: ['There'],
        sound: 'soko',
        tags: [LOCATION],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'あそこ',
        kanji: '',
        en: ['Over there'],
        sound: 'asoko',
        tags: [LOCATION],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'どこ',
        kanji: '',
        en: ['Where'],
        sound: 'doko',
        tags: [LOCATION],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ください',
        kanji: '',
        en: ['Please'],
        sound: 'kudasai',
        tags: [FORMALITY],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
];

export default OTHERS