import { FORMALITY, GREETING, LOCATION, TIME, NUMBER, PERSON } from "../TAGS";
import { OTHER, PARTICLE,KANJI } from "../TYPES";

const defaultWord = [
    {
        jp: '',
        en: [],
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
]

 const OTHERS  = [
    {
        jp: 'じゃないです',
        en: ['Is not'],
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'です',
        en: ['Is'],
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'ごろ',
        en: ['Similar', 'Like'],
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'さよなら',
        en: ['Bye'],
        tags: [GREETING],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'またあした',
        en: ['See you tomorrow'],
        tags: [GREETING],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'おなまえは',
        en: ['Whats your name'],
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'はじめまして',
        en: ['Nice to meet you'],
        tags: [GREETING],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'どうぞよろしく',
        en: ['Nice to meet you'],
        tags: [GREETING],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'しゅっしん',
        en: ['Being from', 'is from'],
        tags: [LOCATION],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        furi: ['はん'],
        jp: '半',
        en: ['Thirty', 'Half'],
        tags: [TIME, NUMBER],
        types: [KANJI, OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        furi: ['く','じ'],
        jp: '九時',
        en: ['Nine o clock'],
        tags: [TIME,NUMBER],
        types: [KANJI, OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        furi: ['しち','じ'],
        jp: '七時',
        en: ['Seven o clock'],
        tags: [TIME,NUMBER],
        types: [KANJI, OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        furi: ['なん'],
        jp:'何',
        en: ['What'],
        tags: [],
        types: [OTHER, KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'じん',
        en: ['Nationality'],
        tags: [PERSON],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        furi: ['じ'],
        jp: '時',
        en: ['o clock'],
        tags: [TIME],
        types: [KANJI, OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'まいあさ',
        en: ['Every morning'],
        tags: [TIME],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'まいにち',
        en: ['Every day'],
        tags: [TIME],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'まいばん',
        en: ['Every night'],
        tags: [TIME],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'を',
        en: ['Through', 'With', 'For'],
        tags: [],
        types: [OTHER],
        notes: ['Goes before verbs'],
        difficulty: 1,
    },
    {
        jp: 'さい',
        en: ['Years old', '(n) of age'],
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'ようこそ',
        en: ['Welcome'],
        tags: [FORMALITY],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'いらっしゃいませ',
        en: ['Welcome'],
        tags: [GREETING, FORMALITY],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'おはようございます',
        en: ['Good morning'],
        tags: [FORMALITY],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'すみません',
        en: ['Excuse me'],
        tags: [FORMALITY],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'いま',
        en: ['Now', 'Current'],
        tags: [TIME],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'どう',
        en: ['What about', 'How is'],
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'も',
        en: ['Also', 'Even', 'Any'],
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        furi: ['わたし'],
        jp: '私',
        en: ['I'],
        tags: [],
        types: [OTHER, PARTICLE, KANJI],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'か',
        en: ['Is it?','That','Or'],
        tags: [],
        types: [OTHER, PARTICLE],
        notes: ['Used at the end to ask something'],
        difficulty: 1,
    },
    {
        jp: 'はい',
        en: ['Yes'],
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'いいえ',
        en: ['No'],
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'じゃあね',
        en: ['Bye'],
        tags: [GREETING],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'さん',
        en: ['Mr','Miss','Mrs'],
        tags: [FORMALITY],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'こんにちは',
        en: ['Hello'],
        tags: [GREETING],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'は',
        en: ['Is','With','Regarding'],
        tags: [],
        types: [OTHER,PARTICLE],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'に',
        en: ['To', 'In', 'As (a)'],
        tags: [],
        types: [OTHER,PARTICLE],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'と',
        en: ['And', 'That', 'Door'],
        tags: [],
        types: [OTHER, PARTICLE],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'の',
        en: ['Of','One'],
        tags: [],
        types: [OTHER, PARTICLE],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'この',
        en: ['This'],
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'その',
        en: ['The','That','Its'],
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'これ',
        en: ['This', 'This (one)','It'],
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'それ',
        en: ['That', 'That (one)'],
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'あれ',
        en: ['That over there', 'That (one) over there'],
        tags: [],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'ここ',
        en: ['Here'],
        tags: [LOCATION],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'そこ',
        en: ['There'],
        tags: [LOCATION],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'あそこ',
        en: ['Over there'],
        tags: [LOCATION],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'どこ',
        en: ['Where'],
        tags: [LOCATION],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
    {
        jp: 'ください',
        en: ['Please'],
        tags: [FORMALITY],
        types: [OTHER],
        notes: [],
        difficulty: 1,
    },
];

export default OTHERS