const defaultWord = [
    {
        kana: '',
        kanji: '',
        en: [],
        sound: '',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
]

 const OTHER  = [
    {
        kana: 'か',
        kanji: '',
        en: ['Is it?','That','Or'],
        sound: 'ka',
        tags: [],
        types: ['other'],
        notes: ['Used at the end to ask something'],
        difficulty: 1,
    },
    {
        kana: 'はい',
        kanji: '',
        en: ['Yes'],
        sound: 'hai',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'いいえ',
        kanji: '',
        en: ['No'],
        sound: 'iie',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'は',
        kanji: '',
        en: ['Is','With','Regarding'],
        sound: '',
        tags: ['particle'],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'じゃあね',
        kanji: '',
        en: ['Bye'],
        sound: 'jyane',
        tags: ['greeting'],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'さん',
        kanji: '',
        en: ['Mr','Miss','Mrs'],
        sound: '',
        tags: ['formality'],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'こんにちは',
        kanji: '',
        en: ['Hello'],
        sound: '',
        tags: ['greeting'],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'と',
        kanji: '',
        en: ['And', 'That', 'Door'],
        sound: 'to',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'これ',
        kanji: '',
        en: ['This', 'This (one)','It'],
        sound: 'kore',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'それ',
        kanji: '',
        en: ['That', 'That (one)'],
        sound: 'sore',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'あれ',
        kanji: '',
        en: ['That over there', 'That (one) over there'],
        sound: 'are',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ここ',
        kanji: '',
        en: ['Here'],
        sound: 'koko',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'そこ',
        kanji: '',
        en: ['There'],
        sound: 'soko',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'あそこ',
        kanji: '',
        en: ['Over there'],
        sound: 'asoko',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'どこ',
        kanji: '',
        en: ['Where'],
        sound: 'doko',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ください',
        kanji: '',
        en: ['Please'],
        sound: 'kudasai',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
];

export default OTHER