const defaultWord = [
    {
        kana: '',
        kanji: '',
        en: '',
        sound: '',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
]

 const OTHER  = [
    {
        kana: 'これ',
        kanji: '',
        en: 'This',
        sound: 'kore',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'それ',
        kanji: '',
        en: 'That',
        sound: 'sore',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'あれ',
        kanji: '',
        en: 'That over there',
        sound: 'are',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ここ',
        kanji: '',
        en: 'Here',
        sound: 'koko',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'そこ',
        kanji: '',
        en: 'There',
        sound: 'soko',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'あそこ',
        kanji: '',
        en: 'Over there',
        sound: 'asoko',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'どこ',
        kanji: '',
        en: 'Where',
        sound: 'doko',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
    {
        kana: 'ください',
        kanji: '',
        en: 'Please',
        sound: 'kudasai',
        tags: [],
        types: ['other'],
        notes: [],
        difficulty: 1,
    },
];

export default OTHER