import TAGS from './TAGS';
import VERB_TENSES from './VERB_TENSES';

import {
  HIRAGANA,
  KATAKANA,
  EN_HIRAGANA_MATCHES,
  EN_KATAKANA_MATCHES,
  KANA_EN_MATCHES,
} from './KANAS';

export {
  EN_HIRAGANA_MATCHES,
  EN_KATAKANA_MATCHES,
  HIRAGANA,
  KATAKANA,
  KANA_EN_MATCHES,
  TAGS,
  VERB_TENSES,
};
